### ISSUE TITLE
Issue with Docker on Windows, Issue with missing directory or file. "load_initial_data" 

### ISSUE THREAD

**Issue by benhadad** [wagtail/bakerydemo#245] opened 2019-08-10 06:31 UTC
I just ran into the same issue on windows. Up until the last issue with the missing directory, there were errors but the process continued. 

docker-compose run app /venv/bin/python manage.py load_initial_data

I can tell part of the issue is when I look in the directory there is not "load_initial_data" file that I can see is available?  Manage.py calls for a file that doesn't exist.

_Originally posted by @benhadad in https://github.com/wagtail/bakerydemo/issues/218#issuecomment-520097260_

**Comment by benhadad** [comment] 2019-08-10 06:33
http://docs.wagtail.io/en/v2.5.1/getting_started/tutorial.html
> Is it possible to add the bakerydemo data to it in an easy way?

**Comment by gasman** [comment] 2019-08-10 09:00
Closing as a duplicate of #218 - please don't open multiple tickets for the same issue.

**Closed by gasman** 2019-08-10 09:00 UTC
