### ISSUE TITLE
Docker demo site nog working?

### ISSUE THREAD

**Issue by Beenhakker** [wagtail/bakerydemo#185] opened 2018-01-24 20:14 UTC
Hi,

I just tried setting up Docker variant of the demo site. I am using Docker 17-12 (stable) on a Macbook Pro, running High Sierra.

The installation seems to be going okay, no clear warnings are show. When going to the homepage when everything runs, displays the default, blank Wagtail page : "Welcome to your new Wagtail site!". Logging in to Wagtail admin also fails with the provided credentials.

I tried to pinpoint what is going on. The Django migrations seem to have ran - the default Django `auth_user` table is empty - I don't know if Wagtail uses this table.

I believe something is broken, or am I missing something?

**Comment by khashashin** [comment] 2018-01-25 13:45
If you just need to try http://cms.smb-web.com/ you can login with >admin >changeme

**Comment by Beenhakker** [comment] 2018-02-01 20:52
Great thanks, I had a look :-)

But I would like to dig a bit more, and look at the code. Is it known issue the Docker version is not working? If so, what's the reason behind it? Maybe easier to update the documentation then. If so, which version is working?

**Comment by vbt101** [comment] 2018-08-31 22:13
I am seeing the same issue on master. One thing I noticed was the following error during the Docker setup. I have not confirmed this is related.

```Postgres is up - continuing
/venv/lib/python3.5/site-packages/dotenv.py:56: UserWarning: Not reading .env - it doesn't exist.
  warnings.warn("Not reading {0} - it doesn't exist.".format(dotenv))
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: SELECT (1) AS "a" FROM "wagtailcore_site" WHERE "wagtailcore...
                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/code/bakerydemo/base/management/commands/load_initial_data.py", line 17, in handle
    if Site.objects.filter(hostname='localhost').exists():
  File "/venv/lib/python3.5/site-packages/django/db/models/query.py", line 715, in exists
    return self.query.has_results(using=self.db)
  File "/venv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 509, in has_results
    return compiler.has_results()
  File "/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1037, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "wagtailcore_site" does not exist
LINE 1: SELECT (1) AS "a" FROM "wagtailcore_site" WHERE "wagtailcore...```

**Comment by vbt101** [comment] 2018-08-31 22:19
As a workaround, after completing the initial Docker setup, I re-ran the following 2 commands. This fixed the login for the admin page, and also allowed the homepage to load with the expected content.

```
docker-compose up --build -d
docker-compose run app /venv/bin/python manage.py load_initial_data
```

**Comment by thibaudcolas** [comment] 2019-07-24 11:10
This seems to be working fine for me while looking at #233 so I’ll close this now, can reopen if the issue reappears. Please copy/paste the relevant logs from the Docker build or runtime errors from Django when reporting issues like this.

**Closed by thibaudcolas** 2019-07-24 11:10 UTC
