### ISSUE TITLE
Style Breads index and detail views

### ISSUE THREAD

**Issue by shacker** [wagtail/bakerydemo#66] opened 2017-02-23 08:35 UTC

**Comment by heymonkeyriot** [comment] 2017-02-23 22:30
I can move on to this tomorrow, but @shacker or @daaray feel free to take if you've time before then.

**Comment by heymonkeyriot** [comment] 2017-02-24 22:08
I'm going to close this as duplicate of #57, which is where I've been adding commits, alongside pull request #71.

**Closed by heymonkeyriot** 2017-02-24 22:08 UTC
