### ISSUE TITLE
Remove psycopg2 requirement

### ISSUE THREAD

**Issue by tomdyson** [wagtail/bakerydemo#116] opened 2017-03-23 14:32 UTC
Many users will want to get bakerydemo running without Vagrant or Docker. You currently have to install the `psycopg2` drivers, which can be a nuisance on OS X (currently failing on my recently updated 10.12.3 OS X). Can we make this optional?

For reference, the existing wagtaildemo repo handles this with an instruction in the README:

https://github.com/wagtail/wagtaildemo#sqlite-support

**Comment by heymonkeyriot** [comment] 2017-03-23 21:20
Good point! I think this is somewhat a duplicate of #65 though. We've been using SQLite through the development of the demo so it should be trivial to make sure that that continues.

**Comment by shacker** [comment] 2017-03-24 06:47
Yes this is parallel to #65  - My hope/intention was to still consider sqlite the default - I assume that most people wanting to check out the demo will want the quickest run path and probably not to populate their local pg server. I also assume that only a very tiny fraction would have interest in hosting the demo on a live server.  Nevertheless, we are still assuming a Heroku dependency, which in turn requires no sqlite, so we have to support postgres. 

So my assumed workflow at this point is:

- demo devs treat the sqlitedb as the master content repo
- we export neutral fixtures from sqlite*
- the readme provides instructions on populating sqlite or postgres from the fixtures

* An alternative, which I'd love your opinion on @tomdyson, is the possibilty of distributing the `bakerydemodb` sqlite file itself with the demo, so most users wouldn't need to import anything. Just download and run. Unorthodoxed, but then it's not often a django project comes with complete starter data. But I'm OK with the fixtures system too. Thoughts?

**Comment by heymonkeyriot** [comment] 2017-03-24 11:19
I know not directed at me, but to throw my hat in to the ring, and I'm surprised saying it, but I think distributing the `bankerydemodb` with the repo could be a good solution. We just need to make sure that we get the `image_renditions` that are currently in there out. In any case I'll defer to whatever @tomdyson thinks would work.

**Comment by shacker** [comment] 2017-03-26 21:40
Ah, great to have your support on this idea @heymonkeyriot - I still think it's a good idea too. If we do this we won't need a data loader, so you're right, deleting image_renditions becomes a manual task again. Not a big deal on that. Standing by for a vote from @tomdyson

**Comment by shacker** [comment] 2017-03-29 07:19
Duplicate discussion starts in #65

**Comment by heymonkeyriot** [comment] 2017-03-29 12:34
It appears that both issues were closed so re-opening this one @shacker . Hope that's okay and I haven't misunderstood something?

I think we can avoid the image_renditions issue being an issue so long as we always remember to delete them from the db before we commit them to the repo. If that isn't the case though then I think we may need to give it a little bit of thought. I can see people feeling a little odd about have to shell in to a db to drop them.

**Comment by shacker** [comment] 2017-03-29 17:02
Oops, thanks for re-opening. 

I don't think you or I will have trouble remembering to do it. I'll add a README note for future devs who might want to add or change images in the set. Either way, it won't be a requirement for demo users.

**Comment by tomdyson** [comment] 2017-03-30 10:51
Sorry @shacker and @heymonkeyriot for the slow response. Thanks for all your excellent work on this so far! Thoughts below:

> I also assume that only a very tiny fraction would have interest in hosting the demo on a live server.

I don't think this is correct. In my experience, plenty of people will use this as a starting point for their production projects (I've seen plenty of live Wagtail sites based on the current wagtaildemo).

> Nevertheless, we are still assuming a Heroku dependency, which in turn requires no sqlite, so we have to support postgres.

Heroku is just one deployment option, not a dependency. Still, you're right, SQLite won't work there.

> So my assumed workflow at this point is:
> - demo devs treat the sqlitedb as the master content repo
> - we export neutral fixtures from sqlite*
> - the readme provides instructions on populating sqlite or postgres from the fixtures

If we treat the SQLite DB as the master content repo, we'll need to keep it in our Git repo, which IMO is undesirable (see below). I think we should use fixtures.

> An alternative, which I'd love your opinion on @tomdyson, is the possibilty of distributing the bakerydemodb sqlite file itself with the demo, so most users wouldn't need to import anything. Just download and run. Unorthodoxed, but then it's not often a django project comes with complete starter data. But I'm OK with the fixtures system too. Thoughts?

I strongly prefer the fixtures approach. I can definitely see the ease-of-use benefits but I think these are outweighed by the disadvantages. In our experience keeping 'compiled' files in source control (e.g. generated CSS files when your source is SASS, or a .sqlite binary when your source is fixtures) becomes painful quickly. SQLite binaries may not be byte-for-byte identical between platforms or versions, which leads to opaque merge conflicts. Using fixtures mean that this demo can be deployed on PostgreSQL, SQLite, MySQL or even MSSQL. 

In the early days of Wagtail we were surprised by how many users didn't conform to our assumed stack of Linux / PostgreSQL / nginx with Vagrant for local development, and a lot of the work in the first few releases was about unpicking those assumptions from the codebase / docs / demo site.

**Comment by shacker** [comment] 2017-04-03 06:51
Thanks Tom. The fixtures-based approach is working nicely now that we've got the export recipe down and worked through the conflicts from WT (logically) creating default initial Site and Page objects in a migration. 

All good, thanks for the feedback.

**Closed by shacker** 2017-04-03 06:51 UTC
